### ISSUE TITLE
MySQL & Read Only

### ISSUE THREAD

**Issue by babielmri** [hggh/wordpress-nagios#1]
Hello,

MySQL is not allowed to run in ReadOnly-mode to run the plugin.

Is it needed to change entries in the database?

Best regards,
Mark

**Comment by hggh** [comment]
I do not query the database. I'm using the wordpress php functions to query the status. perhaps they have problems with read only, but then also wordpress itself have problems?

**Comment by babielmri** [comment]
Yes, it would say so.
Can you give me the names of the functions?
Then I will contact wordpress and ask them why they need to write in the database to check the version of wordpress and plugins.

**Comment by hggh** [comment]
We are using:

wp_update_plugins();
wp_version_check();
wp_update_themes();
$core = get_site_transient('update_core');
$plugins = get_site_transient('update_plugins');
$themes = get_site_transient('update_themes');
